services:
  postgresdb:
    image: postgres:14.5
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ratebooth
    ports:
      - 5432:5432
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_NAME=ratebooth
      - DB_SSL_MODE=disable
    depends_on:
      - postgresdb
    entrypoint: [
      "/app/wait-for.sh",
      "postgresdb:5432",
      "--",
      "/app/start.sh"
    ]
    command: [ "/app/main" ]
