services:
  postgresdb:
    image: postgres:14.5
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ratebooth
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "ratebooth", "-U", "root"]
      interval: 5s
      timeout: 5s
      retries: 5
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - DB_DRIVER=postgres
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_HOST=postgresdb
      - DB_PORT=5432
      - DB_NAME=ratebooth
      - DB_SSL_MODE=disable
      - PORT=8080
    depends_on:
      postgresdb:
        condition: service_healthy
    command: [ "/app/main" ]
