version: '3'

tasks:
  migrate-up:
    cmds:
      - migrate -path db/migration -database "postgresql://root:password@localhost:5432/ratebooth?sslmode=disable" -verbose up

  migrate-down:
    cmds:
      - migrate -path db/migration -database "postgresql://root:password@localhost:5432/ratebooth?sslmode=disable" -verbose down

  sqlc:
    cmds:
      - sqlc generate
  
  test:
    cmds:
      - go test -v -cover -coverprofile=coverage.out ./...

  server:
    cmds:
      - go run main.go

  build-ratebooth-api:
    cmds:
      - docker build -t ratebooth-api:latest .