// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"time"
)

type Booth struct {
	ID           int64  `json:"id"`
	Name         string `json:"name"`
	LogoUrl      string `json:"logo_url"`
	Description  string `json:"description"`
	TwitterUrl   string `json:"twitter_url"`
	InstagramUrl string `json:"instagram_url"`
}

type Rating struct {
	ID        int64     `json:"id"`
	Price     int32     `json:"price"`
	Quality   int32     `json:"quality"`
	CreatedAt time.Time `json:"created_at"`
	BoothID   int64     `json:"booth_id"`
}
